# Generated by Django 4.0 on 2022-05-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
