# Generated by Django 4.0 on 2022-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_userinfo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
