# Generated by Django 4.0 on 2022-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_admin_alter_userinfo_age_alter_userinfo_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default=2, max_length=128, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
