# Generated by Django 4.0 on 2022-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱'),
        ),
    ]
