# Generated by Django 4.0 on 2022-05-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_admin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicestationInfo',
        ),
    ]
