# Generated by Django 4.0 on 2022-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_salesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='axle',
            field=models.CharField(max_length=256, verbose_name='前桥'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='cage',
            field=models.CharField(max_length=256, verbose_name='驾驶室'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='chassisnumber',
            field=models.CharField(max_length=256, verbose_name='底盘号'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='enginemodel',
            field=models.CharField(max_length=128, verbose_name='发动机型号'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='enginenumber',
            field=models.CharField(max_length=256, verbose_name='发动机号'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='name_of_dealer',
            field=models.CharField(max_length=256, verbose_name='经销商名称'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='number_of_failures',
            field=models.CharField(max_length=8, verbose_name='故障数量'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='productioncode',
            field=models.CharField(max_length=256, verbose_name='生产代码'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='productiondata',
            field=models.CharField(max_length=256, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='saletime',
            field=models.CharField(max_length=256, verbose_name='销售日期'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sample_of_vechile',
            field=models.CharField(max_length=32, verbose_name='样本车辆'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='shangdaichuname',
            field=models.CharField(max_length=256, verbose_name='商代处名称'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='terrance',
            field=models.CharField(max_length=32, verbose_name='平台'),
        ),
    ]
