# Generated by Django 4.0 on 2022-05-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_salesdata_axle_alter_salesdata_cage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='axle',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='termianldata',
        ),
    ]
