# Generated by Django 4.0 on 2022-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_remove_salesdata_axle_remove_salesdata_termianldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='claimdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_parts', models.CharField(max_length=128, verbose_name='零件名称')),
                ('chassisnumber', models.CharField(max_length=32, verbose_name='底盘号')),
                ('enginenumber', models.CharField(max_length=32, verbose_name='发动机号')),
                ('subgroupnumber', models.CharField(max_length=16, verbose_name='子组号')),
                ('number_of_parts', models.CharField(max_length=16, verbose_name='零件号')),
                ('productioncode', models.CharField(max_length=32, verbose_name='生产代码')),
                ('productiondata', models.CharField(max_length=128, verbose_name='生产日期')),
                ('saletime', models.CharField(max_length=128, verbose_name='销售日期')),
                ('claimtime', models.CharField(max_length=128, verbose_name='索赔日期')),
                ('moneyclaim', models.CharField(max_length=128, verbose_name='索赔金额')),
                ('materialmoney', models.CharField(max_length=128, verbose_name='材料费')),
                ('mis', models.IntegerField(max_length=32, verbose_name='MIS')),
                ('unitcode', models.CharField(max_length=16, verbose_name='单位编码')),
                ('providercode', models.CharField(max_length=32, verbose_name='供应商代码')),
                ('providername', models.CharField(max_length=256, verbose_name='供应商名称')),
                ('enginemodel', models.CharField(max_length=128, verbose_name='发动机型号')),
                ('drivendistance', models.CharField(max_length=256, verbose_name='行驶里程')),
                ('Faultdescription', models.CharField(max_length=256, verbose_name='故障描述')),
                ('reason', models.CharField(max_length=256, verbose_name='原因分析')),
                ('errorcode', models.CharField(max_length=32, verbose_name='故障代码')),
                ('unitname', models.CharField(max_length=256, verbose_name='单位名称')),
                ('claimnumber', models.CharField(max_length=128, verbose_name='索赔单号')),
                ('servicestationcode', models.CharField(max_length=128, verbose_name='服务站代码')),
                ('servicestationname', models.CharField(max_length=256, verbose_name='服务站名称')),
                ('cage', models.CharField(max_length=256, verbose_name='驾驶室')),
                ('carmodel', models.CharField(max_length=32, verbose_name='车型')),
                ('terrance', models.CharField(max_length=32, verbose_name='平台')),
                ('technicalroute', models.CharField(max_length=32, verbose_name='技术路线')),
                ('sample_of_vechile', models.CharField(max_length=32, verbose_name='样本车辆')),
                ('productmonth', models.CharField(max_length=32, verbose_name='生产月')),
                ('sortedprovidername', models.CharField(max_length=256, verbose_name='整理后的供应商名称')),
                ('sortedprovidercode', models.CharField(max_length=32, verbose_name='整理后的供应商代码')),
                ('sortedname_of_parts', models.CharField(max_length=128, verbose_name='整理后的零件名称')),
            ],
        ),
    ]
