# Generated by Django 4.0 on 2022-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_claimdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdata',
            name='mis',
            field=models.CharField(max_length=32, verbose_name='MIS'),
        ),
    ]
