# Generated by Django 4.0 on 2022-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '紧急'), (2, '临时'), (3, '重要')], default=1, verbose_name='任务级别'),
        ),
    ]
